import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

interface UploadedFile {
  base64: string;
  mimeType: string;
}

const generateSingleMockup = async (
  mainImage: UploadedFile,
  category: string,
  prompt: string,
  customBackground: UploadedFile | null
) => {
  // FIX: The original 'parts' array was being inferred as containing only image parts,
  // causing a type error when adding a text part. This is fixed by creating an
  // array of image parts first, then combining it with the text part, allowing
  // TypeScript to correctly infer the union type for the final array.
  const imageParts = [{
    inlineData: {
      data: mainImage.base64,
      mimeType: mainImage.mimeType,
    },
  }];

  let fullPrompt: string;

  if (customBackground) {
    imageParts.push({
      inlineData: {
        data: customBackground.base64,
        mimeType: customBackground.mimeType,
      },
    });
    fullPrompt = `Using the second image as the background and context, create a photorealistic mockup by realistically applying the first image onto a ${category}. ${prompt}. The integration must be seamless, considering the lighting, perspective, and textures of the background image.`;
  } else {
    fullPrompt = `Create a photorealistic mockup of the provided image on a ${category}. ${prompt}. The mockup should be high-quality, professional, and well-lit.`;
  }
  
  const parts = [...imageParts, { text: fullPrompt }];

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: parts,
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
};

export const generateMockups = async (
  mainImage: UploadedFile,
  category: string,
  prompt: string,
  customBackground: UploadedFile | null
): Promise<string[]> => {
  const promises = Array(4).fill(null).map(() => 
    generateSingleMockup(mainImage, category, prompt, customBackground)
  );

  const results = await Promise.all(promises);
  return results;
};